/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CreateFollowInput: { // input type
    followeeId: number; // Int!
    followerId: number; // Int!
  }
  CreateLikeInput: { // input type
    profileId: number; // Int!
    publishId: number; // Int!
  }
  CreateProfileInput: { // input type
    handle: string; // String!
    imageURI?: string | null; // String
  }
  CreatePublishInput: { // input type
    contentURI: string; // String!
    creatorId: number; // Int!
    description: string; // String!
    imageURI: string; // String!
    metadataURI: string; // String!
    primaryCategory: NexusGenEnums['Category']; // Category!
    secondaryCategory: NexusGenEnums['Category']; // Category!
    tertiaryCategory: NexusGenEnums['Category']; // Category!
    title: string; // String!
  }
  HasRoleInput: { // input type
    role: NexusGenEnums['Role']; // Role!
  }
  UpdateProfileImageInput: { // input type
    imageURI: string; // String!
    profileId: number; // Int!
  }
  UpdatePublishInput: { // input type
    contentURI?: string | null; // String
    creatorId: number; // Int!
    description?: string | null; // String
    imageURI?: string | null; // String
    metadataURI?: string | null; // String
    primaryCategory?: NexusGenEnums['Category'] | null; // Category
    publishId: number; // Int!
    secondaryCategory?: NexusGenEnums['Category'] | null; // Category
    tertiaryCategory?: NexusGenEnums['Category'] | null; // Category
    title?: string | null; // String
  }
}

export interface NexusGenEnums {
  Category: "Animals" | "Children" | "Education" | "Empty" | "Entertainment" | "Food" | "Gaming" | "LifeStyle" | "Men" | "Movies" | "Music" | "News" | "NotExist" | "Other" | "Programming" | "Science" | "Sports" | "Technology" | "Travel" | "Vehicles" | "Women"
  Role: "ADMIN_ROLE" | "DEFAULT_ADMIN_ROLE" | "UPGRADER_ROLE"
  UploadType: "avatar" | "post"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  BurnNFTResult: { // root type
    status: number; // Int!
  }
  CreateFollowResult: { // root type
    followeeId: number; // Int!
    followerId: number; // Int!
    owner: string; // String!
    tokenId: number; // Int!
  }
  CreateLikeResult: { // root type
    owner: string; // String!
    profileId: number; // Int!
    publishId: number; // Int!
    tokenId: number; // Int!
  }
  CreateProfileResult: { // root type
    handle: string; // String!
    imageURI: string; // String!
    owner: string; // String!
    tokenId: number; // Int!
  }
  CreatePublishResult: { // root type
    contentURI: string; // String!
    creatorId: number; // Int!
    imageURI: string; // String!
    likes: number; // Int!
    metadataURI: string; // String!
    owner: string; // String!
    tokenId: number; // Int!
  }
  CreateWalletResult: { // root type
    address: string; // String!
  }
  EstimateCreateNFTGasResult: { // root type
    gas: string; // String!
  }
  MetadataCustomProps: { // root type
    contentURI?: string | null; // String
    handle: string; // String!
    owner: string; // String!
    storagePath?: string | null; // String
    storageURL: string; // String!
    type: NexusGenEnums['UploadType']; // UploadType!
  }
  Mutation: {};
  Query: {};
  UploadParams: { // root type
    address: string; // String!
    fileName: string; // String!
    handle: string; // String!
    mime: string; // String!
    uploadType: NexusGenEnums['UploadType']; // UploadType!
    userId: string; // String!
  }
  UploadReturnType: { // root type
    cid: string; // String!
    storagePath: string; // String!
    storageURL: string; // String!
    tokenURI: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  BurnNFTResult: { // field return type
    status: number; // Int!
  }
  CreateFollowResult: { // field return type
    followeeId: number; // Int!
    followerId: number; // Int!
    owner: string; // String!
    tokenId: number; // Int!
  }
  CreateLikeResult: { // field return type
    owner: string; // String!
    profileId: number; // Int!
    publishId: number; // Int!
    tokenId: number; // Int!
  }
  CreateProfileResult: { // field return type
    handle: string; // String!
    imageURI: string; // String!
    owner: string; // String!
    tokenId: number; // Int!
  }
  CreatePublishResult: { // field return type
    contentURI: string; // String!
    creatorId: number; // Int!
    imageURI: string; // String!
    likes: number; // Int!
    metadataURI: string; // String!
    owner: string; // String!
    tokenId: number; // Int!
  }
  CreateWalletResult: { // field return type
    address: string; // String!
  }
  EstimateCreateNFTGasResult: { // field return type
    gas: string; // String!
  }
  MetadataCustomProps: { // field return type
    contentURI: string | null; // String
    handle: string; // String!
    owner: string; // String!
    storagePath: string | null; // String
    storageURL: string; // String!
    type: NexusGenEnums['UploadType']; // UploadType!
  }
  Mutation: { // field return type
    burnPublishNft: NexusGenRootTypes['BurnNFTResult']; // BurnNFTResult!
    createProfileNft: NexusGenRootTypes['CreateProfileResult']; // CreateProfileResult!
    createPublishNft: NexusGenRootTypes['CreatePublishResult']; // CreatePublishResult!
    createWallet: NexusGenRootTypes['CreateWalletResult']; // CreateWalletResult!
    estimateCreateFollowGas: NexusGenRootTypes['EstimateCreateNFTGasResult']; // EstimateCreateNFTGasResult!
    estimateCreateLikeGas: NexusGenRootTypes['EstimateCreateNFTGasResult']; // EstimateCreateNFTGasResult!
    estimateCreateProfileGas: NexusGenRootTypes['EstimateCreateNFTGasResult']; // EstimateCreateNFTGasResult!
    estimateCreatePublishGas: NexusGenRootTypes['EstimateCreateNFTGasResult']; // EstimateCreateNFTGasResult!
    follow: NexusGenRootTypes['CreateFollowResult']; // CreateFollowResult!
    hasRoleFollow: boolean; // Boolean!
    hasRoleLike: boolean; // Boolean!
    hasRoleProfile: boolean; // Boolean!
    hasRolePublish: boolean; // Boolean!
    like: NexusGenRootTypes['CreateLikeResult']; // CreateLikeResult!
    setDefaultProfile: NexusGenRootTypes['CreateProfileResult']; // CreateProfileResult!
    setFollowContractForProfile: string; // String!
    setLikeContractForPublish: string; // String!
    setLikeFee: string; // String!
    setOwnerAddress: string; // String!
    setPlatformFee: string; // String!
    setProfileContractForFollow: string; // String!
    setProfileContractForLike: string; // String!
    setProfileContractForPublish: string; // String!
    setPublishContractForLike: string; // String!
    unFollow: NexusGenRootTypes['BurnNFTResult']; // BurnNFTResult!
    unLike: NexusGenRootTypes['BurnNFTResult']; // BurnNFTResult!
    updateProfileImage: NexusGenRootTypes['CreateProfileResult']; // CreateProfileResult!
    updatePublishNft: NexusGenRootTypes['CreatePublishResult']; // CreatePublishResult!
    validateHandle: boolean; // Boolean!
    withdrawFunds: string; // String!
  }
  Query: { // field return type
    fetchFollowers: Array<NexusGenRootTypes['CreateFollowResult'] | null>; // [CreateFollowResult]!
    getContractBalance: number; // Float!
    getContractOwnerAddress: string; // String!
    getDefaultProfile: NexusGenRootTypes['CreateProfileResult'] | null; // CreateProfileResult
    getLikeFee: number; // Int!
    getMyBalance: string; // String!
    getMyPublishes: Array<NexusGenRootTypes['CreatePublishResult'] | null>; // [CreatePublishResult]!
    getPlatformFee: number; // Float!
    getPublish: NexusGenRootTypes['CreatePublishResult']; // CreatePublishResult!
    getPublishes: Array<NexusGenRootTypes['CreatePublishResult'] | null>; // [CreatePublishResult]!
    totalPublishes: number; // Int!
  }
  UploadParams: { // field return type
    address: string; // String!
    fileName: string; // String!
    handle: string; // String!
    mime: string; // String!
    uploadType: NexusGenEnums['UploadType']; // UploadType!
    userId: string; // String!
  }
  UploadReturnType: { // field return type
    cid: string; // String!
    storagePath: string; // String!
    storageURL: string; // String!
    tokenURI: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  BurnNFTResult: { // field return type name
    status: 'Int'
  }
  CreateFollowResult: { // field return type name
    followeeId: 'Int'
    followerId: 'Int'
    owner: 'String'
    tokenId: 'Int'
  }
  CreateLikeResult: { // field return type name
    owner: 'String'
    profileId: 'Int'
    publishId: 'Int'
    tokenId: 'Int'
  }
  CreateProfileResult: { // field return type name
    handle: 'String'
    imageURI: 'String'
    owner: 'String'
    tokenId: 'Int'
  }
  CreatePublishResult: { // field return type name
    contentURI: 'String'
    creatorId: 'Int'
    imageURI: 'String'
    likes: 'Int'
    metadataURI: 'String'
    owner: 'String'
    tokenId: 'Int'
  }
  CreateWalletResult: { // field return type name
    address: 'String'
  }
  EstimateCreateNFTGasResult: { // field return type name
    gas: 'String'
  }
  MetadataCustomProps: { // field return type name
    contentURI: 'String'
    handle: 'String'
    owner: 'String'
    storagePath: 'String'
    storageURL: 'String'
    type: 'UploadType'
  }
  Mutation: { // field return type name
    burnPublishNft: 'BurnNFTResult'
    createProfileNft: 'CreateProfileResult'
    createPublishNft: 'CreatePublishResult'
    createWallet: 'CreateWalletResult'
    estimateCreateFollowGas: 'EstimateCreateNFTGasResult'
    estimateCreateLikeGas: 'EstimateCreateNFTGasResult'
    estimateCreateProfileGas: 'EstimateCreateNFTGasResult'
    estimateCreatePublishGas: 'EstimateCreateNFTGasResult'
    follow: 'CreateFollowResult'
    hasRoleFollow: 'Boolean'
    hasRoleLike: 'Boolean'
    hasRoleProfile: 'Boolean'
    hasRolePublish: 'Boolean'
    like: 'CreateLikeResult'
    setDefaultProfile: 'CreateProfileResult'
    setFollowContractForProfile: 'String'
    setLikeContractForPublish: 'String'
    setLikeFee: 'String'
    setOwnerAddress: 'String'
    setPlatformFee: 'String'
    setProfileContractForFollow: 'String'
    setProfileContractForLike: 'String'
    setProfileContractForPublish: 'String'
    setPublishContractForLike: 'String'
    unFollow: 'BurnNFTResult'
    unLike: 'BurnNFTResult'
    updateProfileImage: 'CreateProfileResult'
    updatePublishNft: 'CreatePublishResult'
    validateHandle: 'Boolean'
    withdrawFunds: 'String'
  }
  Query: { // field return type name
    fetchFollowers: 'CreateFollowResult'
    getContractBalance: 'Float'
    getContractOwnerAddress: 'String'
    getDefaultProfile: 'CreateProfileResult'
    getLikeFee: 'Int'
    getMyBalance: 'String'
    getMyPublishes: 'CreatePublishResult'
    getPlatformFee: 'Float'
    getPublish: 'CreatePublishResult'
    getPublishes: 'CreatePublishResult'
    totalPublishes: 'Int'
  }
  UploadParams: { // field return type name
    address: 'String'
    fileName: 'String'
    handle: 'String'
    mime: 'String'
    uploadType: 'UploadType'
    userId: 'String'
  }
  UploadReturnType: { // field return type name
    cid: 'String'
    storagePath: 'String'
    storageURL: 'String'
    tokenURI: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    burnPublishNft: { // args
      publishId: number; // Int!
    }
    createProfileNft: { // args
      input: NexusGenInputs['CreateProfileInput']; // CreateProfileInput!
    }
    createPublishNft: { // args
      input: NexusGenInputs['CreatePublishInput']; // CreatePublishInput!
    }
    estimateCreateFollowGas: { // args
      input: NexusGenInputs['CreateFollowInput']; // CreateFollowInput!
    }
    estimateCreateLikeGas: { // args
      input: NexusGenInputs['CreateLikeInput']; // CreateLikeInput!
    }
    estimateCreateProfileGas: { // args
      input: NexusGenInputs['CreateProfileInput']; // CreateProfileInput!
    }
    estimateCreatePublishGas: { // args
      input: NexusGenInputs['CreatePublishInput']; // CreatePublishInput!
    }
    follow: { // args
      input: NexusGenInputs['CreateFollowInput']; // CreateFollowInput!
    }
    hasRoleFollow: { // args
      data: NexusGenInputs['HasRoleInput']; // HasRoleInput!
    }
    hasRoleLike: { // args
      data: NexusGenInputs['HasRoleInput']; // HasRoleInput!
    }
    hasRoleProfile: { // args
      data: NexusGenInputs['HasRoleInput']; // HasRoleInput!
    }
    hasRolePublish: { // args
      data: NexusGenInputs['HasRoleInput']; // HasRoleInput!
    }
    like: { // args
      input: NexusGenInputs['CreateLikeInput']; // CreateLikeInput!
    }
    setDefaultProfile: { // args
      profileId: number; // Int!
    }
    setFollowContractForProfile: { // args
      followContractAddress: string; // String!
    }
    setLikeContractForPublish: { // args
      likeContractAddress: string; // String!
    }
    setLikeFee: { // args
      fee: number; // Float!
    }
    setOwnerAddress: { // args
      ownerAddress: string; // String!
    }
    setPlatformFee: { // args
      fee: number; // Float!
    }
    setProfileContractForFollow: { // args
      profileContractAddress: string; // String!
    }
    setProfileContractForLike: { // args
      profileContractAddress: string; // String!
    }
    setProfileContractForPublish: { // args
      profileContractAddress: string; // String!
    }
    setPublishContractForLike: { // args
      publishContractAddress: string; // String!
    }
    unFollow: { // args
      tokenId: number; // Int!
    }
    unLike: { // args
      tokenId: number; // Int!
    }
    updateProfileImage: { // args
      input: NexusGenInputs['UpdateProfileImageInput']; // UpdateProfileImageInput!
    }
    updatePublishNft: { // args
      input: NexusGenInputs['UpdatePublishInput']; // UpdatePublishInput!
    }
    validateHandle: { // args
      handle: string; // String!
    }
  }
  Query: {
    getMyBalance: { // args
      address: string; // String!
    }
    getPublish: { // args
      publishId: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}